In [1]:
import pandas as pd
orders = pd.read_csv("../Data/raw/olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [2]:
orders.shape

(99441, 8)

In [3]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [7]:
customers = pd.read_csv("../Data/raw/olist_customers_dataset.csv")
orders_items = pd.read_csv("../Data/raw/olist_order_items_dataset.csv", sep=";")
payments = pd.read_csv("../Data/raw/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../Data/raw/olist_order_reviews_dataset.csv")
products = pd.read_csv("../Data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("../Data/raw/olist_sellers_dataset.csv")
geolocations = pd.read_csv("../Data/raw/olist_geolocation_dataset.csv")
translations = pd.read_csv("../Data/raw/product_category_name_translation.csv", sep=";")

In [8]:
summary = []

datasets = {
    'Orders': orders,
    'Customers': customers,
    'Order Items': orders_items,
    'Payments': payments,
    'Reviews': reviews,
    'Products': products,
    'Sellers': sellers,
    'Geolocations': geolocations,
    'Translations': translations
}

for name, df in datasets.items():
    summary.append({
        'Dataset': name,
        'Rows': df.shape[0],
        'Columns': df.shape[1],
        'Missing Values': df.isnull().sum().sum(),
        'Duplicate Rows': df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

        Dataset     Rows  Columns  Missing Values  Duplicate Rows
0        Orders    99441        8            4908               0
1     Customers    99441        5               0               0
2   Order Items   112650        7               0               0
3      Payments   103886        5               0               0
4       Reviews    99224        7          145903               0
5      Products    32951        9            2448               0
6       Sellers     3095        4               0               0
7  Geolocations  1000163        5               0          261831
8  Translations       71        2               0               0

In [9]:
profiling = []
for name, df in datasets.items():
    profiling.append({
        'Dataset': name,
        'Rows': df.shape[0],
        'Columns': df.shape[1],
        'missing_values': df.isnull().sum().to_dict(),
        'duplicate_rows': df.duplicated().sum(),

    })

profiling_df = pd.DataFrame(profiling)
profiling_df

,Dataset,Rows,Columns,missing_values,duplicate_rows
0,Orders,99441,8,"{'order_id': 0, 'customer_id': 0, 'order_statu...",0
1,Customers,99441,5,"{'customer_id': 0, 'customer_unique_id': 0, 'c...",0
2,Order Items,112650,7,"{'order_id': 0, 'order_item_id': 0, 'product_i...",0
3,Payments,103886,5,"{'order_id': 0, 'payment_sequential': 0, 'paym...",0
4,Reviews,99224,7,"{'review_id': 0, 'order_id': 0, 'review_score'...",0
5,Products,32951,9,"{'product_id': 0, 'product_category_name': 610...",0
6,Sellers,3095,4,"{'seller_id': 0, 'seller_zip_code_prefix': 0, ...",0
7,Geolocations,1000163,5,"{'geolocation_zip_code_prefix': 0, 'geolocatio...",261831
8,Translations,71,2,"{'product_category_name': 0, 'product_category...",0